name: Blue
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29262f'
    - '#c5d6ce'
    - '#008ca7'
    - '#6eb6c4'
    - '#758356'
  brandStrength: 0.8125
  lightness: 0.9700759225524962
  saturation: 0.5
  rhythmicContrast: 0.5609862254932523
purpose: []
