analytics: {}
color:
  brandColors:
    - '#29262f'
    - '#c5d6ce'
    - '#008ca7'
    - '#6eb6c4'
    - '#758356'
  brandStrength: 0.007882
  lightness: 0.5625
  rhythmicContrast: 0.560986
  saturation: 0.296171
cta: {}
layout_spectrum: 0.81698
name: Blue
opengraph: {}
purpose: []
typography_spectrum: 0.26428
